name: "Release Docker Container"
on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
  workflow_dispatch:

jobs:
  clone-repo:
    name: "Clone the repository"
    runs-on: ubuntu-24.04
    steps:
    - name: "checkout"
      uses: actions/checkout@v5
    
    - name: "Docker hub access"
      uses: "../actions/dockerhub-login"
      with:
        dockerhub_username: ${{vars.DOCKERHUB_USERNAME}}
        dockerhub_password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: "Build Docker Image"
      run: docker build -t express-todo-server .
    
    - name: "Push The Docker Image to Dockerhub"
      run: docker push iamridoydey/express-todo-server:latest