name: "Release Docker Container"
on:
  workflow_dispatch:

jobs:
  clone-repo:
    name: "Clone the repository"
    runs-on: ubuntu-24.04
    steps:
    - name: "checkout"
      uses: actions/checkout@v5
    
    - name: "Check the files"
      run: |
          ls -al
    
    - name: "Login to Docker Hub"
      uses: docker/login-action@v3
      with:
        username: ${{vars.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

